### PR TITLE
why tf u use rem for comments lmao

### PR DESCRIPTION
**Pull request by KDot227**
kdot

### CODE REVIEW

**Comment by Sakstacked** [comment]
this nigga didnt give me credit for testing his weak ass logger

**Comment by KDot227** [comment]
> this nigga didnt give me credit for testing his weak ass logger

who

**Comment by Sakstacked** [comment]
nigga named smug

**Comment by KDot227** [comment]
> nigga named smug

why would he give you credit if your testing 💀

**Comment by Sakstacked** [comment]
i found the fucking errorss and shit i asked him if i can be a tester nigga declined me like a bitch no wonder he got a neck for a toilet paper roll

**Comment by KDot227** [comment]
> i found the fucking errorss and shit i asked him if i can be a tester nigga declined me like a bitch no wonder he got a neck for a toilet paper roll

bro u sound dumb asf its open source thats the entire point lmao

**Comment by Sakstacked** [comment]
bro i found some shit that he didnt check or fixed think bitch ass nigga or am on ur ass too hush son this is my businesses

**Comment by KDot227** [comment]
> bro i found some shit that he didnt check or fixed think bitch ass nigga or am on ur ass too hush son this is my businesses

bro u actually dumb asf then make a pr dont bitch bout it

**Comment by Sakstacked** [comment]
drop ur discord matter of fact add me nigga gonna blaze tf out of uf Saks#9902

**Comment by Smug246** [comment]
i had to tell the mf how to get the error up then fixed it myself.

**Comment by KDot227** [comment]
> drop ur discord matter of fact add me nigga gonna blaze tf out of uf Saks#9902

idc enough to add u lmao u just slow asf

**Comment by Sakstacked** [comment]
son stop tryna duck

**Comment by KDot227** [comment]
> son stop tryna duck

U sound like a old head

**Comment by KDot227** [comment]
guess bros an old head

**Comment by KDot227** [comment]
@Smug246 merge cuh

**Comment by Smug246** [comment]
do they need to run as administrator for this to work?

**Comment by KDot227** [comment]
> do they need to run as administrator for this to work?

they don't do they

**Comment by Smug246** [comment]
i'm asking you lol it's your code

**Comment by KDot227** [comment]
> i'm asking you lol it's your code

nah they dont

**Comment by KDot227** [comment]
this kid

**Pull request closed without merging**
