### PR TITLE
Added webcam stealer.

### PR DESCRIPTION
**Pull request by Blank-c**
Only the webcam stealer code is written by me. The upload code was written by Kdot, I simply copied it.

### CODE REVIEW

**Comment by Smug246** [comment]
will add this when i make more options

**Comment by Smug246** [comment]
also @Blank-c  just tested and it just gives me a black screen...

**Comment by Blank-c** [comment]
> also @Blank-c just tested and it just gives me a black screen...

Do you have a webcam? Is it simulated?

**Comment by Smug246** [comment]
just 1 and it's not inbuilt. it's a logitech one i forgot its name

**Comment by Blank-c** [comment]
Avicam32 is obsolete so maybe that is the issue. I cannot port to Directshow just yet.

**Comment by Smug246** [comment]
ah ok

**Comment by Smug246** [comment]
uh nvm its kinda weird @Blank-c . sometimes the picture will be black and sometimes it will work. im not sure what it depends on

**Comment by Blank-c** [comment]
> im

Yea actually this API is outdated. One can use other APIs but they all depend on 3rd party libraries.

**Comment by Smug246** [comment]
np ill keep looking, thanks though

**Comment by Dariusispro** [comment]
.

**Pull request closed without merging**
