### PR TITLE
Add disclaimer about illegal use of the tool

### PR DESCRIPTION
**Pull request by maxfire2008**

### CODE REVIEW

**Comment by maxfire2008** [comment]
> you should replace the header [#] with [>] to make it still visible, but smaller.

This made it too small - I made it an h3 instead.

**Comment by komet60** [comment]
what to do when the program does not start? python is installed and the "run.bat" file is run as administrator.

**Review by Serpensin — APPROVED** [review]

**Comment by syberontop** [comment]
When is this tool illegal?

**Comment by maxfire2008** [comment]
> When is this tool illegal?

Updated the disclaimer slightly to be more clear.

**Review by Serpensin — APPROVED** [review]

**Pull request closed without merging**
